In [1]:
import os
from dotenv import load_dotenv
load_dotenv()

True

In [10]:
#!pip3 install faiss-cpu numpy sentence-transformers


In [3]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

# Sample documents
documents = [
    "The cat sits on the mat.",
    "The dog plays with the ball.",
    "A bird is flying in the sky.",
    "The sun is shining bright today.",
]

# Query
query = "Tell me about animals."

# Load pre-trained SentenceTransformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Compute embeddings
doc_embeddings = model.encode(documents)
query_embedding = model.encode([query])

# Compute cosine similarity between query and documents
similarities = cosine_similarity(query_embedding, doc_embeddings).flatten()

# Get top-n results (e.g., top 3)
top_n = 3
top_indices = similarities.argsort()[-top_n:][::-1]

# Display results
print("Query:", query)
print("\nTop Relevant Documents:")
for idx in top_indices:
    print(f"Document: {documents[idx]} (Score: {similarities[idx]:.4f})")


Query: Tell me about animals.

Top Relevant Documents:
Document: The dog plays with the ball. (Score: 0.1942)
Document: A bird is flying in the sky. (Score: 0.1890)
Document: The cat sits on the mat. (Score: 0.0617)


In [9]:
from llama_index.embeddings.openai import OpenAIEmbedding
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Initialize the OpenAI embedding model
embedding_model = OpenAIEmbedding(model="text-embedding-ada-002")

# Define the trivia questions and matching answers
phrases = [
    "Who was the first president of the United States?",
    "What is the capital city of France?",
    "In what year did humans first land on the moon?",
    "Which element on the periodic table has the chemical symbol O?",
    "What is the largest planet in the solar system?",
    "The first president of the United States was George Washington.",
    "The capital city of France is Paris.",
    "Humans first landed on the moon in the year 1969.",
    "The chemical symbol O represents the element Oxygen.",
    "The largest planet in the solar system is Jupiter."
]

# Generate embeddings for each phrase using OpenAI embeddings
embeddings = embedding_model.get_text_embedding_batch(phrases)

# Convert embeddings to a numpy array
embeddings_array = np.array(embeddings)

# Print the first phrase and the first several elements of its embedding
print(f"Phrase: {phrases[0]}")
print(f"First 5 elements of its embedding: {embeddings_array[0][:5]}\n")

# Compute cosine similarity between the embeddings
similarity_matrix = cosine_similarity(embeddings_array)

# Print the cosine similarity matrix
print("Cosine Similarity Matrix:")
print(np.round(similarity_matrix, 2))
print("\nDetailed Similarity Results:\n")

# Output comparison between phrases with improved readability
for i in range(len(phrases)):
    print("\n---------------------------------------------------------")
    for j in range(i + 1, len(phrases)):
        print(f"Cosine similarity between:\n  '{phrases[i]}'\n  and\n  '{phrases[j]}'\n  => {similarity_matrix[i, j]:.4f}\n")

Phrase: Who was the first president of the United States?
First 5 elements of its embedding: [-0.00530775 -0.02198926 -0.01972655 -0.02283176 -0.00803384]

Cosine Similarity Matrix:
[[1.   0.78 0.83 0.76 0.76 0.92 0.75 0.78 0.72 0.73]
 [0.78 1.   0.74 0.75 0.77 0.75 0.94 0.72 0.73 0.73]
 [0.83 0.74 1.   0.75 0.78 0.78 0.72 0.93 0.72 0.74]
 [0.76 0.75 0.75 1.   0.77 0.73 0.74 0.73 0.93 0.75]
 [0.76 0.77 0.78 0.77 1.   0.72 0.75 0.75 0.73 0.93]
 [0.92 0.75 0.78 0.73 0.72 1.   0.79 0.78 0.74 0.76]
 [0.75 0.94 0.72 0.74 0.75 0.79 1.   0.74 0.76 0.78]
 [0.78 0.72 0.93 0.73 0.75 0.78 0.74 1.   0.74 0.76]
 [0.72 0.73 0.72 0.93 0.73 0.74 0.76 0.74 1.   0.75]
 [0.73 0.73 0.74 0.75 0.93 0.76 0.78 0.76 0.75 1.  ]]

Detailed Similarity Results:


---------------------
Cosine similarity between:
  'Who was the first president of the United States?'
  and
  'What is the capital city of France?'
  => 0.7790

Cosine similarity between:
  'Who was the first president of the United States?'
  and
  'In 